In [268]:
import sys
!{sys.executable} -m pip install numpy pandas matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (2.5.3)
Requirement already satisfied: pandas in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (3.0.6)
Requirement already satisfied: matplotlib in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (3.11.2)
Requirement already satisfied: seaborn in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\ntjam\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [269]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [270]:
# Load the datasets
accounts = pd.read_csv(r"D:\Amdari\Project_finlora\Data\Raw\finlora_accounts.csv")
transactions = pd.read_csv(r"D:\Amdari\Project_finlora\Data\Raw\finlora_transactions.csv")

print("Accounts shape:    ", accounts.shape)
print("Transactions shape:", transactions.shape)

Accounts shape:     (7200, 8)
Transactions shape: (126000, 24)

In [271]:
# Accounts table
accounts.head()

,account_id,account_holder_name,account_type,home_country,currency,kyc_tier,account_created_date,personal_spend_baseline_usd
0,FLR-ACC-100000,Amaka Okafor,Individual,NG,NGN,Tier3_Enhanced,2022-08-28,63.23
1,FLR-ACC-100001,Bluewave Foods Ltd,Business,NG,NGN,Tier1_Basic,2026-04-27,810.68
2,FLR-ACC-100002,Global Trading LLC,Business,US,USD,Tier2_Verified,2026-03-29,433.67
3,FLR-ACC-100003,Femi Adeyemi,Individual,NG,NGN,Tier3_Enhanced,2025-09-15,19.18
4,FLR-ACC-100004,Ngozi Brown,Individual,NG,NGN,Tier3_Enhanced,2024-06-18,28.68

In [272]:
accounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7200 entries, 0 to 7199
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   account_id                   7200 non-null   str
 1   account_holder_name          7200 non-null   str
 2   account_type                 7200 non-null   str
 3   home_country                 7200 non-null   str
 4   currency                     7200 non-null   str
 5   kyc_tier                     7200 non-null   str
 6   account_created_date         7200 non-null   str
 7   personal_spend_baseline_usd  7200 non-null   float64
dtypes: float64(1), str(7)
memory usage: 450.1 KB

In [273]:
# Transactions table
transactions.head()

,transaction_id,account_id,account_type,kyc_tier,timestamp,day_of_week,hour_of_day,description,merchant_name,merchant_category,...,avg_transaction_amount_30d,transaction_velocity_1h,transaction_country,home_country,is_cross_border,device_id,is_new_device,account_age_days,status,is_fraud
0,FLR250216186265,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-02-16 14:55:35,Sunday,14,CNP PURCHASE - BOLT,Bolt,Travel,...,9143.33,0,NG,NG,0,NaN,NaN,903,Completed,0
1,FLR250423143305,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-23 13:35:40,Wednesday,13,WEB PURCHASE - SLACK,Slack,Subscription/SaaS,...,9143.33,0,NG,NG,0,NaN,NaN,969,Declined,0
2,FLR250424154897,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-24 12:30:34,Thursday,12,MOBILE PURCHASE - JUSTRITE SUPERSTORE,Justrite Superstore,Groceries,...,9143.33,0,NG,NG,0,DEV-9055235108,0.0,970,Completed,0
3,FLR250428101772,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-28 14:41:59,Monday,14,CNP PURCHASE - ADOBE CREATIVE CLOUD,Adobe Creative Cloud,Subscription/SaaS,...,14891.16,0,NG,NG,0,NaN,NaN,974,Completed,0
4,FLR250628102827,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-06-28 16:15:47,Saturday,16,MOBILE PURCHASE - APPLE STORE,Apple Store,Electronics,...,49609.59,0,NG,NG,0,DEV-9055235108,0.0,1035,Declined,0

In [274]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 24 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   transaction_id              126000 non-null  str
 1   account_id                  126000 non-null  str
 2   account_type                126000 non-null  str
 3   kyc_tier                    126000 non-null  str
 4   timestamp                   126000 non-null  str
 5   day_of_week                 126000 non-null  str
 6   hour_of_day                 126000 non-null  int64
 7   description                 126000 non-null  str
 8   merchant_name               97390 non-null   str
 9   merchant_category           126000 non-null  str
 10  channel                     126000 non-null  str
 11  amount                      126000 non-null  float64
 12  currency                    126000 non-null  str
 13  amount_to_avg_ratio         126000 non-null  float64
 14  avg_transaction_amount_30d  126000 non-null  float64
 15  transaction_velocity_1h     126000 non-null  int64
 16  transaction_country         126000 non-null  str
 17  home_country                126000 non-null  str
 18  is_cross_border             126000 non-null  int64
 19  device_id                   111666 non-null  str
 20  is_new_device               111666 non-null  float64
 21  account_age_days            126000 non-null  int64
 22  status                      126000 non-null  str
 23  is_fraud                    126000 non-null  int64
dtypes: float64(4), int64(5), str(15)
memory usage: 23.1 MB

In [275]:
# Missing values
print("Accounts table: missing values")
print(accounts.isna().sum())
print("\nTranscations table: missing values")
print(transactions.isna().sum())

# Duplicates
print("\nDuplicates")
print("Accounts - duplicate rows:", accounts.duplicated().sum())
print("Accounts - duplicate account_id:", accounts['account_id'].duplicated().sum())
print("Transactions - duplicate rows:", transactions.duplicated().sum())
print("Transactions - duplicate transaction_id:", transactions['transaction_id'].duplicated().sum())

Accounts table: missing values
account_id                     0
account_holder_name            0
account_type                   0
home_country                   0
currency                       0
kyc_tier                       0
account_created_date           0
personal_spend_baseline_usd    0
dtype: int64

Transcations table: missing values
transaction_id                    0
account_id                        0
account_type                      0
kyc_tier                          0
timestamp                         0
day_of_week                       0
hour_of_day                       0
description                       0
merchant_name                 28610
merchant_category                 0
channel                           0
amount                            0
currency                          0
amount_to_avg_ratio               0
avg_transaction_amount_30d        0
transaction_velocity_1h           0
transaction_country               0
home_country                      0
is_cross_border                   0
device_id                     14334
is_new_device                 14334
account_age_days                  0
status                            0
is_fraud                          0
dtype: int64

Duplicates
Accounts - duplicate rows: 0
Accounts - duplicate account_id: 0
Transactions - duplicate rows: 0
Transactions - duplicate transaction_id: 0

In [276]:
missing = transactions.isna().sum()
print(missing[missing > 0])

merchant_name    28610
device_id        14334
is_new_device    14334
dtype: int64

In [277]:
print("Negative amounts:", (transactions["amount"] < 0).sum())
print("Negative 30-day avg:", (transactions["avg_transaction_amount_30d"] < 0).sum())

Negative amounts: 291
Negative 30-day avg: 144

In [278]:
# Categories of missing values
transactions.loc[transactions["merchant_name"].isna(), "merchant_category"].value_counts()

merchant_category
Payroll Transfer     17117
P2P Transfer         10715
Groceries              112
Retail                  98
Subscription/SaaS       97
Utilities               97
Restaurants             69
Travel                  63
Wire Transfer           55
Electronics             47
ATM Withdrawal          42
Insurance               39
Healthcare              36
Crypto Exchange         14
Gambling/Gaming          9
Name: count, dtype: int64

In [279]:
# Clean accounts dataset 
# Change the date column from string to real datetime
accounts["account_created_date"] = pd.to_datetime(accounts["account_created_date"], errors="coerce")

# Verify
print("Unparseable dates:", accounts["account_created_date"].isna().sum())
print("Date range:", accounts["account_created_date"].min(),"->", accounts["account_created_date"].max())

Unparseable dates: 0
Date range: 2021-12-25 00:00:00 -> 2026-08-29 00:00:00

In [280]:
# Clean transaction dataset

# Change timestamp from string to datetime
transactions["timestamp"] = pd.to_datetime(transactions["timestamp"], errors="coerce")

# Missing merchant_name 
merchantless = transactions["merchant_category"].isin(["P2P Transfer", "Payroll Transfer"])
transactions.loc[merchantless & transactions["merchant_name"].isna(),"merchant_name"] = "N/A - No Merchant"
transactions["merchant_name"] = transactions["merchant_name"].fillna("Unknown")

# Missing device_id / is_new_device (always missing together)
transactions["is_device_known"] = transactions["is_new_device"].notna().astype(int)
transactions["device_id"] = transactions["device_id"].fillna("Unknown_device")
transactions["is_new_device"] = transactions["is_new_device"].fillna(0).astype(int)

# Negative amounts 
transactions["amount"] = transactions["amount"].abs()

# Negative 30-day average 
transactions["avg_transaction_amount_30d"] = transactions["avg_transaction_amount_30d"].abs()

# Recompute amount_to_avg_ratio so it stays consistent after sign fixes
safe = transactions["avg_transaction_amount_30d"] > 0
transactions.loc[safe, "amount_to_avg_ratio"] = (transactions.loc[safe, "amount"] / transactions.loc[safe, "avg_transaction_amount_30d"]).round(2)

print("Cleaning complete.")
print("Missing values remaining:", transactions.isna().sum().sum())
print("Negative amounts:", (transactions["amount"] < 0).sum())
print("Fraud rate:", round(transactions["is_fraud"].mean() * 100, 3), "%")

Cleaning complete.
Missing values remaining: 0
Negative amounts: 0
Fraud rate: 2.66 %

In [281]:
# Merging datasets.
# (account_type & kyc_tier already exist in transactions and match, so skip them.
#  home_country & currency also already exist in transactions, so skip them too.)
account_cols = ["account_id", "account_holder_name", "account_created_date", "personal_spend_baseline_usd",]

merged = transactions.merge(
    accounts[account_cols],
    on="account_id",     # match rows where account_id is the same
    how="left",          # keep all transactions, attach account info where found
    validate="many_to_one",   # safety check: many transactions -> one account
)

print("Transactions shape:", transactions.shape)
print("Merged shape:      ", merged.shape)
print("Rows unchanged:", len(merged) == len(transactions))
print("New missing values from merge:", merged[account_cols[1:]].isna().sum().sum())

Transactions shape: (126000, 25)
Merged shape:       (126000, 28)
Rows unchanged: True
New missing values from merge: 0

In [282]:
merged.to_csv(r"D:\Amdari\Project_finlora\Data\Processed\finlora_merged_clean.csv", index=False)
print("Saved merged dataset:", merged.shape)

Saved merged dataset: (126000, 28)

In [283]:
merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 126000 entries, 0 to 125999
Data columns (total 28 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   transaction_id               126000 non-null  str
 1   account_id                   126000 non-null  str
 2   account_type                 126000 non-null  str
 3   kyc_tier                     126000 non-null  str
 4   timestamp                    126000 non-null  datetime64[us]
 5   day_of_week                  126000 non-null  str
 6   hour_of_day                  126000 non-null  int64
 7   description                  126000 non-null  str
 8   merchant_name                126000 non-null  str
 9   merchant_category            126000 non-null  str
 10  channel                      126000 non-null  str
 11  amount                       126000 non-null  float64
 12  currency                     126000 non-null  str
 13  amount_to_avg_ratio          126000 non-null  float64
 14  avg_transaction_amount_30d   126000 non-null  float64
 15  transaction_velocity_1h      126000 non-null  int64
 16  transaction_country          126000 non-null  str
 17  home_country                 126000 non-null  str
 18  is_cross_border              126000 non-null  int64
 19  device_id                    126000 non-null  str
 20  is_new_device                126000 non-null  int64
 21  account_age_days             126000 non-null  int64
 22  status                       126000 non-null  str
 23  is_fraud                     126000 non-null  int64
 24  is_device_known              126000 non-null  int64
 25  account_holder_name          126000 non-null  str
 26  account_created_date         126000 non-null  datetime64[us]
 27  personal_spend_baseline_usd  126000 non-null  float64
dtypes: datetime64[us](2), float64(4), int64(7), str(15)
memory usage: 26.9 MB

In [284]:
merged.head()

,transaction_id,account_id,account_type,kyc_tier,timestamp,day_of_week,hour_of_day,description,merchant_name,merchant_category,...,is_cross_border,device_id,is_new_device,account_age_days,status,is_fraud,is_device_known,account_holder_name,account_created_date,personal_spend_baseline_usd
0,FLR250216186265,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-02-16 14:55:35,Sunday,14,CNP PURCHASE - BOLT,Bolt,Travel,...,0,Unknown_device,0,903,Completed,0,0,Amaka Okafor,2022-08-28,63.23
1,FLR250423143305,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-23 13:35:40,Wednesday,13,WEB PURCHASE - SLACK,Slack,Subscription/SaaS,...,0,Unknown_device,0,969,Declined,0,0,Amaka Okafor,2022-08-28,63.23
2,FLR250424154897,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-24 12:30:34,Thursday,12,MOBILE PURCHASE - JUSTRITE SUPERSTORE,Justrite Superstore,Groceries,...,0,DEV-9055235108,0,970,Completed,0,1,Amaka Okafor,2022-08-28,63.23
3,FLR250428101772,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-04-28 14:41:59,Monday,14,CNP PURCHASE - ADOBE CREATIVE CLOUD,Adobe Creative Cloud,Subscription/SaaS,...,0,Unknown_device,0,974,Completed,0,0,Amaka Okafor,2022-08-28,63.23
4,FLR250628102827,FLR-ACC-100000,Individual,Tier3_Enhanced,2025-06-28 16:15:47,Saturday,16,MOBILE PURCHASE - APPLE STORE,Apple Store,Electronics,...,0,DEV-9055235108,0,1035,Declined,0,1,Amaka Okafor,2022-08-28,63.23

In [285]:
# EDA